errors.mqtt.topic = "te/errors"

input.mqtt.topics = [
    "tbflow/device/+/+/+/m/+",
    "tbflow/device/+/+/+/twin/+",
    "tbflow/device/+/+/+/a/+",
    "tbflow/device/+/+/+/e/+",
    "tbflow/device/+/+/+/status/health"
]

[[steps]]
builtin = "add-timestamp"
config.property = "time"
config.format = "unix"
config.reformat = true

[[steps]]
script = "lib/main.js"

interval = "10m"
config.add_type_to_key = "${.params.add_type_to_key}"
config.alarm_prefix = "${.params.alarm_prefix}"
config.event_prefix = "${.params.event_prefix}"
config.enable_heartbeat = "${.params.enable_heartbeat}"
