[input.process]
# Each interval, get the next 5 log messages for a given service
# Use a cursor-file (built-in journalctl functionality) to remember the last
# log entry processed.
#
# The output is piped to grep to filter out the "No entries" output from journalctl,
# and then finally piped to cat to avoid exiting with a non-zero exit code.
command = """sudo journalctl -o json -b --cursor-file=/tmp/log-surge-cursor --no-pager -n 1000"""
interval = "300s"

[[steps]]
script = "lib/main.js"
interval = "600s"

config.with_logs = "${params.with_logs}"
config.debug = "${params.debug}"
config.stats_topic = "${params.stats_topic}"
config.publish_statistics = "${params.publish_statistics}"
config.threshold.total = "${params.threshold_total}"
config.threshold.error = "${params.threshold_error}"
config.threshold.warning = "${params.threshold_warning}"
config.threshold.info = "${params.threshold_info}"

# Optional log message filter, which will only include log entries
# where the message text matches the given regex
config.text_filter = "${params.text_filter}"
