input_topics = ["te/device/main///logs/journald"]

[[steps]]
script = "dist/main.mjs"
tick_every_seconds = 1

config.with_logs = true
config.debug = false
config.publish_statistics = true
config.stats_topic = "stats/logs"
config.threshold.total = 0
config.threshold.error = 1
config.threshold.warning = 1
config.threshold.info = 10

# Optional log message filter, which will only include log entries
# where the message text matches the given regex
# config.text_filter = ["(connect)"]
