[input]
mqtt.topics = [
    "te/device/main/service/mosquitto-c8y-bridge/status/health",
    "te/device/main/service/tedge-mapper-bridge-c8y/status/health",
]

[[steps]]
script = "dist/main.mjs"
interval = "10s"
config.window_size_minutes = 1440
config.stats_topic = "twin/onlineTracker"
config.default_status = "uninitialized"
