input_topics = [
    "te/device/main/service/mosquitto-c8y-bridge/status/health",
    "te/device/main/service/tedge-mapper-bridge-c8y/status/health",
]

[[steps]]
filter = "dist/main.mjs"
tick_every_seconds = 10
config.window_size_minutes = 1440
config.stats_topic = "twin/onlineTracker"
config.default_status = "uninitialized"
