name: Test Node.js Projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  discover-projects:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.find-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format:check

      - id: find-projects
        name: Find Node.js projects
        run: |
          # Find all directories under `pipelines` that contain a package.json,
          # then format the list as a JSON array for the matrix strategy.
          PROJECTS=$(find pipelines -name package.json -exec dirname {} \; | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "projects=$PROJECTS" >> $GITHUB_OUTPUT

  test:
    needs: discover-projects
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.actor }}

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.discover-projects.outputs.projects) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "${{ matrix.project }}/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.project }}

      - name: Run tests
        run: npm test
        working-directory: ${{ matrix.project }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: npm run publish -- ${{ matrix.project }}

  test-summary:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Report overall status
        run: echo "All project tests passed successfully."
